version: "3.9"
services:
  gem_bot:
    build: .
    container_name: ${TG_BOT_NAME}
    depends_on:
      - db
    restart: always
    volumes:
      - ./voices:/voices
    ports:
      - "8199:80"
    networks:
      gem_net:
        ipv4_address: 172.55.61.11

  db:
    image: postgres:latest
    container_name: ${TG_BOT_NAME}_bd
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ../postgres-backup:/backup
    networks:
      psy_net:
        ipv4_address: 172.55.61.12

  pgadmin:
    image: dpage/pgadmin4
    container_name: ${TG_BOT_NAME}_pgadmin
    restart: unless-stopped
    ports:
      - "8091:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "tdallstr@yandex.ru"
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      gem_net:
        ipv4_address: 172.55.61.13

networks:
  gem_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.55.61.0/24